
name: "Deploy"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
permissions: write-all
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.6.0

      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      - run: |
          npm install
          npm audit fix

      - name: Build project
        run: |
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.WEBKEY }}
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.WEBKEY }}
          publish_dir: ./dist
